;------------------------------------------------------------------------------
; Words Replacer
;------------------------------------------------------------------------------
; Replaces common words with simpler or more bimbo-like versions. (ie. "best" => "bestest", "confused" => "ditzy"...)

loadWordReplacer(state) {
	if (state == true) {
		Hotstring("B Z0")
		Hotstring("::okay", "okie")
		Hotstring("::ok", "okie")
		Hotstring("::oki", "okie")
		Hotstring("::delicious", "yummy")
		Hotstring("::tasty", "yummy")
		Hotstring("::best", "bestest")
		Hotstring("::better", "bettah")
		Hotstring("::god", "dog")
		Hotstring("::wow", "oh dog")
		Hotstring("::probably", "totally")
		Hotstring("::girls", "puppygirlz")
		hotstring("::woman", "puppygirl")
		hotstring("::women", "puppygirlz")
		Hotstring("::dumb", "dum")
		Hotstring("::confused", "silly")
		Hotstring("::very", "so")
		Hotstring("::thus", "so")
		Hotstring("::really", "rly")
		Hotstring("::though", "tho")
		Hotstring("::through", "thru")
		Hotstring("::thanks", "thankies")
		Hotstring("::whatever", "whatevz")
		Hotstring("::am", "is")
		Hotstring("::everybody", "everypuppy")
		Hotstring("::food", "treats")
		Hotstring("::walk", "walkies")
		Hotstring("::hand", "paw")
		Hotstring("::hands", "paws")
		Hotstring("::mouth", "snout")
		Hotstring("::feminize", "puppify")
		Hotstring("::feminized", "puppified")
		Hotstring("::human", "puppy")
		Hotstring("::clique", "pack")
		Hotstring("::group", "pack")
		Hotstring("::persona", "puppysona")
		Hotstring("::hair", "fur")
		Hotstring("::touch", "bap")
		Hotstring("::touches", "baps")
        Hotstring("::smack", "bap")
        Hotstring("::smacks", "baps")
        Hotstring("::slap", "bap")
        Hotstring("::slaps", "baps")
		Hotstring("reset")
	}
}